
# --- Configurações Gerais ---
# Habilita modo de navegação com teclas do Vi
set-window-option -g mode-keys vi
# Desabilita renomeação automática de janelas para manter os nomes que você definir
set-window-option -g automatic-rename off
set-option -g allow-rename off

# Altera o prefixo padrão de C-b para C-x
unbind C-b
set-option -g prefix C-x
bind-key C-a send-prefix

# Renumera as janelas quando uma é fechada
set-option -g renumber-windows on
# Aumenta o histórico de scrollback
set-option -g history-limit 50000

# Habilita o uso do mouse
set -g mouse on

# Começa a contagem de janelas e painéis do 1 em vez do 0
set -g base-index 1
setw -g pane-base-index 1

# <prefix> r (reload) - Recarrega o .tmux.conf
bind r run-shell -b '\
  tmux source-file ~/.config/tmux/tmux.conf ; \
  tmux display-message "Config reloaded 🌀..."; \
'

# <prefix> Ctrl+f (Lista) - Lista seções com fzf
bind C-f run-shell '\
  tmux list-window -a -F "##S:##I ##W ##P ##D" |
  fzf --sync --tmux center |
  awk "{print \$1}" |
  xargs tmux switch-client -t
'

# --- Atalhos de Teclado (Keybindings) ---
# Inicia a busca no modo de cópia
bind-key / copy-mode \; send-key ?
bind-key KP/ copy-mode \; send-key ?
bind-key -T copy-mode-vi / copy-mode \; send-key ?
bind-key -T copy-mode-vi KP/ copy-mode \; send-key ?

bind-key C-p display-popup -E -w 60% -h 60% "ipython"
bind-key C-h display-popup -E -w 80% -h 80% "btop"
# <prefix> Ctrl+t (terminal) - Abre o terminal normal em um popup
bind-key C-t display-popup -E -w80% -h80% ""
# <prefix> Ctrl+x (just run) - Roda o just com recipe run (ESC sai)
bind-key C-x display-popup -w80% -h80% "just run"

# Atalhos SEM PREFIXO para navegar entre janelas com Alt+Número e Alt+n/p
bind -n M-n select-window -n
bind -n M-p select-window -p
#
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Atalho para salvar o conteúdo de um painel em um arquivo temporário
bind-key v 'capture-pane' \; run "tmux capture-pane -pJ -S- -E-|sed -E 's| *$||' >/tmp/tmux" \; display "Buffer saved to /tmp/tmux!" \;

# --- Plugins (Gerenciados pelo TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # Restauração automática
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'          # <--- ADICIONADO para a RAM
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux' # <-- MUDANÇA AQUI

# Configuração do Continuum
set -g @continuum-restore 'on' # Habilita a restauração automática ao iniciar o tmux
# Salva em 5min
set -g @continuum-save-interval '5'
# --- Configurações do Dracula ---
set -g @dracula-plugins "host battery ram-usage session-name time"
set -g @dracula-show-powerline true
set -g @dracula-time-format "%a %d/%m %H:%M" # Formato: Seg 22/09 10:14
# --- Inicialização do TPM ---
# (Deve ser a ÚLTIMA linha do arquivo)
run '~/.tmux/plugins/tpm/tpm'
