[FileDialog]
history=file:///opt/intelFPGA/21.1/questa_fse/gcc-7.4.0-linux_x86_64, file:///home/eax/Documents/Faculdade/mecatronica/6Fase/eletronicaDigital, file:///home/eax/Documents/Faculdade/mecatronica/6Fase/eletronicaDigital/teste/db, file:///home/eax/Documents/Faculdade/mecatronica/6Fase/eletronicaDigital/tarefas, file:///home/eax/Documents/Faculdade/mecatronica/6Fase/eletronicaDigital/tarefas/tarefa11
lastVisited=file:///home/eax/Documents/Faculdade/mecatronica/6Fase/eletronicaDigital/tarefas/tarefa11
qtVersion=5.15.9
shortcuts=file:, file:///home/eax
sidebarWidth=126
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xae\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1)\0\0\0\x1\0\0\0\0\0\0\0g\0\0\0\x1\0\0\0\0\0\0\0g\0\0\0\x1\0\0\0\0\0\0\0\xb7\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
